export const data = [
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: true,
    id: 1,
  },
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: false,
    id: 2,
  },
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: false,
    id: 1,
  },
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: false,
  },
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: false,
  },
  {
    discount: { isDiscount: true, procent: '50%' },
    rating: null,
    urlProduct: '/',
    urlImg: '/images/Arrivals/img1.webp',
    title: 'Loveseat Sofa',
    statusNew: true,
    favorite: false,
  },
];
